# Generated by Django 3.0.2 on 2020-02-26 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200225_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assi_name', models.CharField(max_length=50)),
                ('assi_last_name', models.CharField(max_length=50)),
                ('assi_dni', models.CharField(max_length=10, unique=True)),
                ('assi_email', models.EmailField(max_length=254, unique=True)),
                ('assi_phone', models.CharField(max_length=20)),
                ('assi_address', models.CharField(max_length=100)),
                ('assi_description', models.TextField()),
                ('assi_tau', models.CharField(max_length=20, unique=True)),
                ('assi_status', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Pausa')], default=1)),
                ('assi_create_at', models.DateTimeField(auto_now_add=True)),
                ('assi_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_code', models.CharField(max_length=50, unique=True)),
                ('case_name', models.CharField(max_length=50)),
                ('case_description', models.TextField()),
                ('case_estatus', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Pausa'), (3, 'Ganado'), (4, 'Perdido')], default=1)),
                ('case_start_date', models.DateField()),
                ('case_end_date', models.DateField()),
                ('case_final_date', models.DateField()),
                ('case_cost', models.FloatField()),
                ('case_create_at', models.DateTimeField(auto_now_add=True)),
                ('case_modified_at', models.DateTimeField(auto_now=True)),
                ('case_assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Assistant')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clie_name', models.CharField(max_length=50)),
                ('clie_last_name', models.CharField(max_length=50)),
                ('clie_dni', models.CharField(max_length=10, unique=True)),
                ('clie_email', models.EmailField(max_length=254, unique=True)),
                ('clie_phone', models.CharField(max_length=20)),
                ('clie_address', models.CharField(max_length=100)),
                ('clie_create_at', models.DateTimeField(auto_now_add=True)),
                ('clie_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawy_name', models.CharField(max_length=50)),
                ('lawy_last_name', models.CharField(max_length=50)),
                ('lawy_dni', models.CharField(max_length=10, unique=True)),
                ('lawy_email', models.EmailField(max_length=254, unique=True)),
                ('lawy_phone', models.CharField(max_length=20)),
                ('lawy_address', models.CharField(max_length=100)),
                ('lawy_description', models.TextField()),
                ('lawy_tau', models.CharField(max_length=20, unique=True)),
                ('lawy_status', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo'), (2, 'Pausa')], default=1)),
                ('lawy_create_at', models.DateTimeField(auto_now_add=True)),
                ('lawy_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('type_description', models.TextField()),
                ('type_status', models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('type_create_at', models.DateTimeField(auto_now_add=True)),
                ('type_modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='user_create_at',
            new_name='perm_create_at',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='user_modified_at',
            new_name='perm_modified_at',
        ),
        migrations.AddField(
            model_name='user',
            name='user_file',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%D/'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sche_name', models.CharField(max_length=50)),
                ('sche_description', models.TextField()),
                ('sche_status', models.IntegerField(choices=[(0, 'Cancelado'), (1, 'Activo'), (2, 'Pausa'), (3, 'Logrado'), (4, 'Incumplido')], default=1)),
                ('sche_color', models.CharField(max_length=8)),
                ('sche_start', models.DateTimeField()),
                ('sche_duration', models.IntegerField()),
                ('sche_create_at', models.DateTimeField(auto_now_add=True)),
                ('sche_modified_at', models.DateTimeField(auto_now=True)),
                ('sche_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reco_name', models.CharField(max_length=50)),
                ('reco_description', models.TextField()),
                ('reco_file', models.FileField(blank=True, upload_to='documents/%Y/%m/%D/')),
                ('reco_date', models.DateTimeField()),
                ('reco_create_at', models.DateTimeField(auto_now_add=True)),
                ('reco_modified_at', models.DateTimeField(auto_now=True)),
                ('reco_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paym_amount', models.FloatField()),
                ('paym_date', models.DateTimeField()),
                ('paym_create_at', models.DateTimeField(auto_now_add=True)),
                ('paym_modified_at', models.DateTimeField(auto_now=True)),
                ('paym_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Client'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Lawyer'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Type_case'),
        ),
    ]
