# Generated by Django 3.0.2 on 2020-02-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20200226_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_file',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
