# Generated by Django 3.0.2 on 2020-02-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20200227_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_estatus',
            new_name='case_status',
        ),
    ]
