# Generated by Django 3.0.2 on 2020-02-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20200227_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_cost',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='reco_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sche_duration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_file',
            field=models.ImageField(blank=True, default='images/noimage.jpg', upload_to='images/%Y/%m/%d/'),
        ),
    ]
